version: '3.3'

services:
  react-app:
    build: client
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - express-app

  express-app:
    build: server
    restart: always
    ports:
      - "8080:8080"

